### ISSUE TITLE
Please consider joining Hacktoberfest

### ISSUE THREAD

**Issue by gmacario** [Three-Buddy-Problem/exoplanet-quest-web#4]
I wonder whether you are aware about [Hacktoberfest 2024](https://hacktoberfest.com/) which is happening as we speak.
IMHO Hacktoberfest is an excellent way of making your project known and soliciting independendent contributors.

Speaking for myself, I have been participating in Hacktoberfest for the last 8 years.
Additionally, since 2023 I have served as maintainer for a few projects of the [B-AROL-O Team organization](https://github.com/B-AROL-O) which thanks to Hacktoberfest have already received contributions from all over the world.

I would definitely recommend you to consider adding the "Hacktoberfest" label to https://github.com/Three-Buddy-Problem/exoplanet-quest-web and https://github.com/Three-Buddy-Problem/exoplanet-quest-terminal as well!

**Comment by kaandesu** [comment]
Hello, yess I've personally heard about it, - also reminded about it the other day from the badges on your profile 😄 -. Since yesterday I have been thinking about a way to make it actively contributable/maintainable, because I uploaded a workflow that would deploy the current progress to the production site on every commit on the 'main' branch, I didn't think that would be fair for the other global contestants of the 2024 NASA Space Apps Challenge even if it was permitted. 
However, I was considering creating a 'master' branch, making it the primary one, and adding a disclaimer about the version submitted to the global contest, and making it open for contribution, that way the contents of the link we submitted wouldn't change while developing.

**Comment by gmacario** [comment]
> However, I was considering creating a 'master' branch, making it the primary one, and adding a disclaimer about the version submitted to the global contest, and making it open for contribution, that way the contents of the link we submitted wouldn't change while developing.

Sounds like a good plan. As a side benefit the project will evolve irrespectively of the judging period of the global NASA Space Apps Challenge!

**Comment by kaandesu** [comment]
I've set up the 'master' branch with the disclaimer along with the hacktoberfest tag 🎊 , I'll also further update the readme with more info once I have the time 👍

**Comment by gmacario** [comment]
> I've set up the 'master' branch with the disclaimer along with the hacktoberfest tag 🎊

Great! Please just make sure you fix the spelling of the "Hac**k**toberfest" label in the "About" section of [the project](https://github.com/Three-Buddy-Problem/exoplanet-quest-web)

![image](https://github.com/user-attachments/assets/ac8ce985-9cda-4b42-9d83-bbd03daa6f63)

If you don't, PRs to this repo will not be accounted for the challenge 😢 
FTR: I made the same mistake with one of my repositories in the past😄

>, I'll also further update the readme with more info once I have the time 👍

When you do, make the change through a Pull Request (not just committing to the main branch) *after* you have registered to the Hacktoberfest (Yes, even PRs to your own repo count!)

**Comment by kaandesu** [comment]
Done, thank you! 👍 

_i fell victim to github's autocomplete 😄_

**Comment by gmacario** [comment]
I consider the issue resolved, also because my PR https://github.com/Three-Buddy-Problem/exoplanet-quest-web/pull/5 has just been accepted by https://hacktoberfest.com/ 🎉 🎉 

![image](https://github.com/user-attachments/assets/8cbcd726-9bfa-42e4-a188-3c288e4845db)
